### PR TITLE
Code rework.

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by Wolf3s** [comment]
I will fork your prboom-plus repo then merge these changes from there even with cmake_iop available.

**Comment by 7dog123** [comment]
Alright thanks and take your time. I know you must have other things you gotta do.

**Comment by Wolf3s** [comment]
Yes, There is a lot of stuff.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 7dog123** [comment]
Yeah, so take your time.

**Comment by Wolf3s** [comment]
> Yeah, so take your time.

I ported prboom-plus and i will migrate again to dsda-doom(Due to lack of SDL_GameController).

**Pull request merged**
